### ISSUE TITLE
Module ignores MySQL SSL Setting

### ISSUE THREAD

**Issue by neubi4** [Icinga/icingaweb2-module-reporting#18]
## Describe the bug

The module ignores the 'use_ssl = "1"' setting in the resources.ini file and trys to connect to the mysql server without ssl.

## To Reproduce

MySQL Privileges:
```
ALTER USER 'user'@'localhost' REQUIRE SSL;
ALTER USER 'user'@'%' REQUIRE SSL;
```

resouces.ini
```
[reporting_db]
type = "db"
db = "mysql"
host = "mysql-host"
port = "3306"
dbname = "icingaweb2reporting"
username = "user"
password = "asdasd"
charset = "utf8"
use_ssl = "1"
ssl_ca = "/etc/domon_ca/ca_cert.pem"
```

## Expected behavior

Module connect with the given SSL settings to mysql server.

## Screenshots

Error thrown:
![reporting_module](https://user-images.githubusercontent.com/1274627/57833076-82e1c500-77b9-11e9-95ab-8001e83aa2db.PNG)

```
SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.25.0.7' (using password: YES)

#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(146): PDO->__construct(String, String, String, Array)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(161): ipl\Sql\Connection->createPdoAdapter()
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(312): ipl\Sql\Connection->connect()
#3 /usr/share/icingaweb2/modules/reporting/library/Reporting/RetryConnection.php(13): ipl\Sql\Connection->prepexec(String, Array)
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(331): Icinga\Module\Reporting\RetryConnection->prepexec(String, Array)
#5 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php(41): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->indexAction()
#7 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/icingaweb2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#12 {main}

```

## Your Environment

* Module version: 
* Dependent module versions: master 660777dbeccbaa925fc9ed5c90f3078d68519481
* Icinga Web 2 version and modules (System - About): 2.6.2
* Web browser and version: Chrome 73
* Icinga 2 version used (`icinga2 --version`): 2.10.4
* PHP version used (`php --version`):  7.2.17
* Server operating system and version: CentOS 7.6.1810

## Additional context

In Icingaweb2 all other MySQL Connections (icinga2 db, director db) are using ssl to connect to mysql, with the same configuration.

**Comment by nilmerg** [comment]
Thanks for the report, though this needs to be supported in the ipl-sql library: https://github.com/Icinga/ipl-sql/issues/9
