### ISSUE TITLE
Filename cannot be empty

### ISSUE THREAD

**Issue by ItMeCorban** [Icinga/icingaweb2-module-reporting#238]
DELETE ME

**Comment by ItMeCorban** [comment]
Ok most of that can be disregarded, I tried the debian install again and seems much better now, however I've now stuck with 
```
Fatal error: Uncaught ErrorException: Uncaught Zend_View_Exception: script 'layout.phtml' not found in path (/usr/share/icingaweb2/application/layouts/scripts/:/usr/share/icingaweb2/application/layouts/scripts/:/usr/share/icingaweb2/application/views/scripts/) in /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/View/Abstract.php:986 Stack trace: #0 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/View/Abstract.php(882): Zend_View_Abstract->_script('layout.phtml') #1 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Layout.php(796): Zend_View_Abstract->render('layout.phtml') #2 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Layout/Controller/Plugin/Layout.php(143): Zend_Layout->render() #3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Plugin/Broker.php(332): Zend_Layout_Controller_Plugin_Layout->postDispatch(Object(Icinga\Web\Request)) #4 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Fron in /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Plugin/Broker.php on line 262
```
