### ISSUE TITLE
idoreports_get_sla_ok_percent does not exist

### ISSUE THREAD

**Issue by megol** [Icinga/icingaweb2-module-reporting#29]
## Describe the bug

After the installation of Reporting module setting database for reporting which is different between icinga_ido database.

When I'm openning Reporting tab after all configuration and choosing before configured report - I see an error:

```
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION icinga.idoreports_get_sla_ok_percent does not exist, query was: SELECT h.display_name COLLATE latin1_general_ci AS host_display_name, s.display_name COLLATE latin1_general_ci AS service_display_name, h.display_name COLLATE latin1_general_ci AS host_display_name, s.display_name COLLATE latin1_general_ci AS service_display_name, idoreports_get_sla_ok_percent(so.object_id, '2019-07-01 00:00:00', '2019-07-01 10:16:55', NULL) AS sla FROM icinga_objects AS so
 INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
 INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id ORDER BY h.display_name COLLATE latin1_general_ci ASC, s.display_name COLLATE latin1_general_ci ASC (Pdo.php:225)

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /usr/share/icingaweb2/modules/idoreports/library/Idoreports/IdoReport.php(208): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 /usr/share/icingaweb2/modules/idoreports/library/Idoreports/ServiceSlaReport.php(70): Icinga\Module\Idoreports\IdoReport->fetchServiceSla(Object(Icinga\Module\Reporting\Timerange), Array)
#5 /usr/share/icingaweb2/modules/idoreports/library/Idoreports/IdoReport.php(27): Icinga\Module\Idoreports\ServiceSlaReport->fetchSla(Object(Icinga\Module\Reporting\Timerange), Array)
#6 /usr/share/icingaweb2/modules/reporting/library/Reporting/Report.php(263): Icinga\Module\Idoreports\IdoReport->getHtml(Object(Icinga\Module\Reporting\Timerange), Array)
#7 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(41): Icinga\Module\Reporting\Report->toHtml()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->indexAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}

```

It seems that the Reporting module is trying to connect to the icinga_objects which is in the icinga main database... 
Reporting DB has only: 

mysql> show tables;
+---------------------+
| Tables_in_reporting |
+---------------------+
| config              |
| report              |
| reportlet           |
| schedule            |
| timeframe           |
+---------------------+
5 rows in set (0.00 sec)

and no icinga_object table there because in install notes we should create NEW Database reporting and insert mysql.sql from schema directory.

Any idea how to solve this issue?

Thanks.

**Comment by dnsmichi** [comment]
Please look into the documentation for the `idoreports` module. It requires you to import specific procedures into the icinga database.

https://icinga.com/docs/reporting/latest/idoreports/doc/02-Installation/#import-database-files

**Comment by megol** [comment]
Thanks @dnsmichi 

It solved my problem here.
