### ISSUE TITLE
Improve error logging for PDF exports

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2-module-reporting#6]
# Current Behaviour

![Screen Shot 2019-04-17 at 13 29 30](https://user-images.githubusercontent.com/382049/56284931-3c476f00-6116-11e9-9dcb-372064672500.png)

# Steps to Reproduce

- Setup IPL, reactbundle, pdfexport as dependencies
- Don't have chrome headless installed
- Create a new host sla report and try to export the PDF

# Possible Solution

- Enhance the stack trace and error message
- Both conditions with `isSupported()` and raw should be extended. Maybe the pdfexport module can return an error code and a string where it explains the reasoning, e.g. that Chrome headless is missing.

```
2019-04-17T13:29:16+02:00 - ERROR - Exception in /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php:117 with message: Can't export
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#6 {main}
```

```
                if (Hook::has('Pdfexport')) {
                    $pdfexport = Hook::first('Pdfexport');

                    if (! $pdfexport->isSupported()) {
                        throw new \Exception("Can't export");
                    }
                }

                if (! $pdfexport) {
                    throw new \Exception("Can't export");
                }
```

# Versions involved

- Module version: v0.9.0
- Icinga Web 2 version: 2.6.2, 14b6e4056231e12b4826432dfd7d5c60796e08b2
- Dependent modules: 

```
icinga::ipl::version:                   "v0.2.1"
icinga::reactbundle::version:           "v0.5.1"
icinga::pdfexport::version:             "v0.9.0"
icinga::reporting::version:             "v0.9.0"
icinga::idoreports::version:            "v0.9.0"
```

**Comment by lippserd** [comment]
Will be fixed with the latest releases of this module, pdfexport and Web itself.
