### ISSUE TITLE
Pdfexport not working as expected

### ISSUE THREAD

**Issue by Raboebie** [Icinga/icingaweb2-module-reporting#61]
When running an export of a report the webui simply produces a stack trace complaining that Pdfexport::first() is an undefined method. I have all of the dependencies installed and chrome headless is working as expected.

1. Select a report
2. Select dropdown and export as PDF
3. Stack trace is shown

The PDF should be generated.

Uncaught Error: Call to undefined method Icinga\Module\Pdfexport\ProvidedHook\Pdfexport::first() in /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php:118
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('downloadAction')
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#6 {main}
thrown

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

![image](https://user-images.githubusercontent.com/4992098/80141109-59c0db80-85a9-11ea-91d5-845f88537b12.png)

* Module version: 0.10.0 reporting, 
* Dependent module versions:  0.9.1 pdfexport, reactbundle v0.6.0, ipl v0.5.0
* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser and version: Version 81.0.4044.122 (Official Build) (64-bit)
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): PHP 7.0.33-0ubuntu0.16.04.14
* Server operating system and version: Ubuntu 16.04 Server

**Comment by nilmerg** [comment]
Hi,

the current master is not compatible with the latest release of the pdfexport module. You have to also install the master of the pdfexport module.

**Comment by Raboebie** [comment]
Thanks for the info, did not know that. I installed the master as you said. It changed my error at least.

`Uncaught TypeError: Return value of iio\libmergepdf\Merger::addRaw() must be an instance of iio\libmergepdf\void, none returned in /usr/share/icingaweb2/modules/pdfexport/vendor/iio/libmergepdf/src/Merger.php:41
Stack trace:
#0 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/ProvidedHook/Pdfexport.php(92): iio\libmergepdf\Merger->addRaw('%PDF-1.4\n%\xD3\xEB\xE9\xE1\n...')
#1 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(118): Icinga\Module\Pdfexport\ProvidedHook\Pdfexport->streamPdfFromHtml(Object(Icinga\Module\Pdfexport\PrintableHtmlDocument), 'Daily landscape...')
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('downloadAction')
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Obje

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}`

Any suggestions?

**Comment by nilmerg** [comment]
Well, it seems a library (libmergepdf) we're utilizing does not support older PHP versions than 7.1.

Though, I can't tell if you if this persists to be the case with the next release. But for now you'd have to upgrade to PHP 7.1 for the pdfexport master to work.

**Comment by Raboebie** [comment]
Great, thank you very much. Let me give that a go and report back.
