### ISSUE TITLE
Error with Postgresql Backend

### ISSUE THREAD

**Issue by fl0wx** [Icinga/icingaweb2-module-reporting#76]
## Describe the bug

If i use a postgresql Backend i get the following error while trying to open the reports page:

```
Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /usr/share/icingaweb2/modules/reporting/library/Reporting/Database.php:20
Stack trace:
#0 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php(41): Icinga\Module\Reporting\Controllers\ReportsController->getDb()
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->indexAction()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_onc

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

if i install the php7.x-mysql Module (which shouldnt be necessary in my opinion, because i only use postgresql as backend) then i get another Error:

```
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near ""utf8""
LINE 1: SET NAMES "utf8"
^
#0 [internal function]: PDO->exec(String)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(82): call_user_func_array(Array, Array)
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(164): ipl\Sql\Connection->__call(String, Array)
#3 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(312): ipl\Sql\Connection->connect()
#4 /usr/share/icingaweb2/modules/reporting/library/Reporting/RetryConnection.php(13): ipl\Sql\Connection->prepexec(String, Array)
#5 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(331): Icinga\Module\Reporting\RetryConnection->prepexec(String, Array)
#6 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php(41): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->indexAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}
```
## To Reproduce

use postgresql as backend

## Expected behavior

It should work

## Your Environment

* Module version: v0.9.2
* Dependent module versions: 

director | 1.7.2
doc | 2.7.3
grafana | 1.3.6
idoreports | 0.9.0
incubator | 0.5.0
ipl | v0.3.0
monitoring | 2.7.3
pdfexport | 0.9.0
reactbundle | 0.7.0
reporting | 0.9.2

* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser and version: Chrome 84
* Icinga 2 version used (`icinga2 --version`):  r2.11.3-1
* PHP version used (`php --version`): PHP 7.3.19-1~deb10u1
* Server operating system and version: Debian GNU/Linux 10 (buster)

**Comment by fl0wx** [comment]
After downloading php7.3-mysql and upgrading ipl to 0.5.0 it seems to work for not. But i dont want to install php-mysql just to get a postgres backend to work. Please investigate in this issue

**Comment by nilmerg** [comment]
This is likely the same as reported in https://github.com/Icinga/icingaweb2-module-x509/pull/85#issuecomment-723655049
